default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1
  host: localhost

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: blogpost_development
  username: postgres
  password: 1
  host: localhost

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>