default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: temir
  password: 1
  host: localhost
  port: 5432

development:
  <<: *default
  database: BlogPost

test:
  <<: *default
  database: BlogPostTest

production:
  <<: *default
  database: Production
  username: temir
  password: <%= ENV['DATABASE_PASSWORD'] %>